### ISSUE TITLE
Setup examples for guides

### ISSUE THREAD

**Issue by TheDutchCoder** [TheDutchCoder/webpack-guides-code-examples#1]
Roadmap:

- [x] Init project
- [x] add `.gitignore`
- [x] add `README`
- [x] add `Getting Started` starter examples
- [x] add `Asset Management` starter examples
- [x] add `Output Management` starter examples
- [x] add `Development` starter examples

**Comment by TheDutchCoder** [comment]
Alright, just merged in the `development` examples and all your PR's as well @skipjack .

I think we're well underway right now, which is great!

I might do another pass over all the guides/examples I've done so far to see if I missed any details and/or errors made in the process.

**Comment by skipjack** [comment]
Sounds great 👍
